---
urls:
  - https://www.newegg.com/msi-geforce-gtx-1050-ti-gtx-1050-ti-biaofeng-4g/p/1FT-0009-004U8
  - https://www.newegg.com/xfx-radeon-rx-6800-xt-rx-68xtacbd9/p/N82E16814150844
  - https://www.newegg.com/msi-geforce-rtx-2060-rtx-2060-gaming-z-6g/p/N82E16814137379
  - https://www.newegg.com/asus-geforce-gtx-1650-dual-gtx1650-o4gd6-mini/p/N82E16814126451
  - https://www.newegg.com/gigabyte-geforce-gtx-1050-ti-gv-n105toc-4gd/p/N82E16814125915
  - https://www.newegg.com/asus-geforce-rtx-2080-ti-rog-strix-rtx2080ti-o11g-gaming/p/N82E16814126263
...